# Generated by Django 4.0.2 on 2022-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_drivers_vehicle_name_alter_drivers_vehicle_no_and_more'),
    ]



