# Generated by Django 4.0.6 on 2023-02-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_details'),
        ('service', '0027_merge_20221222_1047'),
    ]

    operations = [
    ]
