# Generated by Django 4.0.6 on 2023-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_merge_0002_details_0027_merge_20221222_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='parceldetails',
            name='delivery_hand',
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='receiver_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
